export const institutionAdminConstants = {
  INSTITUTION_ADMIN_REGISTER_REQUEST: 'INSTITUTION_ADMIN_REGISTER_REQUEST',
  INSTITUTION_ADMIN_REGISTER_SUCCESS: 'INSTITUTION_ADMIN_REGISTER_SUCCESS',
  INSTITUTION_ADMIN_REGISTER_FAILURE: 'INSTITUTION_ADMIN_REGISTER_FAILURE',

  INSTITUTION_ADMIN_GETALL_REQUEST: 'INSTITUTION_ADMIN_GETALL_REQUEST',
  INSTITUTION_ADMIN_GETALL_SUCCESS: 'INSTITUTION_ADMIN_GETALL_SUCCESS',
  INSTITUTION_ADMIN_GETALL_FAILURE: 'INSTITUTION_ADMIN_GETALL_FAILURE',

  INSTITUTION_ADMIN_GETBYID_REQUEST: 'INSTITUTION_ADMIN_GETBYID_REQUEST',
  INSTITUTION_ADMIN_GETBYID_SUCCESS: 'INSTITUTION_ADMIN_GETBYID_SUCCESS',
  INSTITUTION_ADMIN_GETBYID_FAILURE: 'INSTITUTION_ADMIN_GETBYID_FAILURE'
};
